### ISSUE TITLE
License and Maven Central

### ISSUE THREAD

**Issue by jdramsey** [meyerjp3/psychometrics#10]
Is there license for this project? If not, is it OK if I include some code from it in a project I'm working on? I would prefer just to grab it from Maven Central, but I can't find it there. Is there a plan to upload it there so it can be included in projects? My workaround is to import all fo the code into my project, which I can do and properly credit and all, but just using the Maven dependency would be the best. Unfortunately, I can't figure out a way to just import the jar into my project, not for lack of trying.

**Comment by wbuchanan** [comment]
@jdramsey
Check the maven documentation for installing a jar locally.  Then you can include it in your pom file to manage the dependency.

**Comment by jdramsey** [comment]
@wbuchanan I will try again. I was not having luck. The project seems designed to prevent that. :( 

Have yu chosen a license? May I assume GPL some version?

**Comment by jdramsey** [comment]
@wbuchanan Sorry, that is, the project _I'm_ working on seems designed to prevent local file inclusion. Maven always complains and won't compile. Is it OK to put a mirror on one of our servers? I think I can include it that way.

**Comment by meyerjp3** [comment]
Sorry for the very long delay. The library is licensed under the Apache License, Version 2.0. You are welcome to try and put a mirror on your local server.

**Comment by jdramsey** [comment]
Thanks!
