### ISSUE TITLE
How can I get api about psychometrics

### ISSUE THREAD

**Issue by Sohnia** [meyerjp3/psychometrics#11]
The url  you gave isn't useful,due to apis been removed.My English is so poor,
please forgive me.

**Comment by wbuchanan** [comment]
It isn’t clear what you are looking for, which URL isn’t sufficient, or what kind of API you are trying to locate.  Perhaps you can provide more details?

**Comment by Sohnia** [comment]
http://itemanalysis.com/api,this url.

**Comment by Sohnia** [comment]
It's nothing.http://itemanalysis.com/api/psychometrics

**Comment by wbuchanan** [comment]
I think you may just need to compile/build the library locally and can view the Javadocs that way.

**Comment by Sohnia** [comment]
I am a Chinese student studying about IRT in university,so just want to know how your programs to work.Early on,I can open the website of apis.I very appreciate it that your reply.

**Comment by meyerjp3** [comment]
I uploaded the most recent API. You can access it here, https://itemanalysis.com/psychometrics-javadoc/1.4/. I've also updated the link on the main GitHub page.
