### ISSUE TITLE
Factor Analysis on Polychoric Correlation Matrix?

### ISSUE THREAD

**Issue by pereferrera** [meyerjp3/psychometrics#4]
Hello,
I came across your library searching for factor analysis software in Java.
I am trying to see if it is possible to conduct factor analysis over categorical variables using this library, as suggested here in the first answer: http://stats.stackexchange.com/questions/32234/reference-on-factor-analysis-with-categorical-variables

But as I am not well versed in this subject I am not sure: Is it possible? If so, could you provide a small hint on how to try it?

**Comment by meyerjp3** [comment]
It is possible, but I don't have a working example. You will first need to estimate polychoric correlations using the classes in the com.itemanalysis.psychometrics.polycor package. You can then provide the polychoric correlation matrix as input into the exploratory factor analysis class that is in the com.itemanlaysis.psychometrics.factoranalysis package. You can see example of each part separately in the test classes, but you will have to combine the parts to get the functionality you seek.

**Comment by pereferrera** [comment]
Thanks a lot. The test cases are very clear. I just realized my data is not really ordinal, but rather nominal. So I'm not sure if I will end up using the polychoric correlation matrix. I've read there are other methods like the "latent class factor analysis" which handle nominal data better. Is this method implemented or planned to be implemented?
On the other hand I had the idea that I could treat every nominal value as a different binary variable for factor analysis. What's your take on this idea? Sorry to abuse of your knowledge, and many thanks in advance.

**Comment by meyerjp3** [comment]
Yes, you could treat each response to a nominal variable as a separate binary variable. You could then use tetrachoric correlations and exploratory factor analysis. The tetrachoric correlations are just a special case of the polychoric correlations.
