### ISSUE TITLE
It not working. how do i debug to find out error

### ISSUE THREAD

**Issue by parveenmani** [meyerjp3/psychometrics#7]
optimizer.optif9_f77(n, x, minclass, typsiz, fscale, method, iexp, msg, ndigit, itnlim,
                iagflg, iahflg, dlt, gradtl, stepmx, steptl, xpls, fpls, gpls, itrmcd, a, udiag); 

is notworking

**Comment by meyerjp3** [comment]
This code is a Java translation of a FORTRAN program. I didn't write the program. If you include an example of how it does not work, I will help you trouble shoot the problem. However, consider using DefaultUncminOptimizer.java instead. It provides a better interface to optimizer.optif9_f77.

**Comment by parveenmani** [comment]
Sir,
i am thankful to you for your reply
can you please provide the format of input file given to IRT project.
i want to give value manually. in short i want to know where should i enter
value.
presently i have made some changes in "ItemResponseFileSummary.java"
i am giving value to line[0]=1 line[2]=1
i just wanted find out value of theta by providing level of difficulty and
is correct

**Comment by meyerjp3** [comment]
Please review the test cases to learn how to use the classes. For item calibration, see the MarginalMaximumLiklihoodEstimationTest.java class and for person scoring see IrtExamineeTest.java. They both can be found in https://github.com/meyerjp3/psychometrics/tree/master/src/test/java/com/itemanalysis/psychometrics/irt/estimation

**Comment by parveenmani** [comment]
Sir,
What does this item stands for?? is it difficulty?
I want to give following inputs
Question is correct or not (1/0)
Difficulty (1 to 5)
Ability of a person
Depending upon this value i wanted to calculate or update ability of a
person. in such scenario which classes should i mainly use.

one more query. if their are 5 types of difficulty leven then their would
be 5 types of ability of a person. M i correct??

**Comment by meyerjp3** [comment]
The items are the item responses. O or 1 for binary items. 0, 1, 2, and so on for polytomous items.

**Comment by parveenmani** [comment]
sir,
can you please help me out.
i need to create an interface which basically takes two inputs
1) is correct (answer is correct or not means 0 or 1)
2) difficulty level (we have 5 difficulty level from 1 to 5)
and i have to find out ability/theta using these inputs. i am already
reading all classes but time is a constraint.
can you please guide which classes should i concentrate on to achieve my
target.

i would be thankful and it would be a great help.


Regards
Ms Parveen Sharma

**Comment by wbuchanan** [comment]
How did you obtain the difficulty estimates and why are they ordinal?  Why not estimate the item parameters and theta simultaneously instead of constraining the difficulty parameters to values a priori?  Maybe if you are able to provide a bit more context (e.g., purpose, types of items/response scales, how the discrimination parameter is estimated and/or why there are difficulty parameter estimates without discrimination parameter estimates, etc...) Dr Meyer and/or other users following the repository might be able to provide you with answers that are more relevant to your particular context.

**Comment by parveenmani** [comment]
Sir,
As per your Guidance i have calculated theta from "IrtExaminee  (and method
pcfEstimate ) " am i correct or doing wrong
but i have a doubt it would be correct or not.
what i am doing is :
passing binary value to Line[] MMLESimulator,then i am calling

String[] line = new String[5];
        ArrayList<ItemResponseVector> responseData = new
ArrayList<ItemResponseVector>();
        byte[] rv = null;
        ItemResponseVector irv = null;
        ItemResponseVector[] itemResponseVector = null;
                line[0]="1";
        line[1]="0";
        line[2]="0";
        line[3]="0";
        line[4]="0";

                rv=new byte[5];

                for(int j=0;j<5;j++)

                {

                    rv[j] = Byte.parseByte(line[j]);

                }
                irv = new ItemResponseVector(rv, 1.0);
                responseData.add(irv);


            itemResponseVector = new
ItemResponseVector[responseData.size()];


            for(int i=0;i<responseData.size();i++){
                itemResponseVector[i] = responseData.get(i);

            }


            try{
            ItemResponseModel irm=new ItemResponseModel();
        IrtExaminee ie= new IrtExaminee(irm,itemResponseVector);
            }
            catch(DimensionMismatchException ex)
            {
            ex.printStackTrace();

            }

and then using  pcfEstimate  to get theta value....
please guide???

**Comment by parveenmani** [comment]
Sir,
Which class has connection between ability and difficulty.
if one answer first question correct that what would be value of theta.?? i
just want to cross check the value

**Comment by parveenmani** [comment]
Sir,
I am using IrtExaminee to calculate theta , how can i use adjustment and
xmin and xmax.
i have response as binary i.e 0 for incorrect and 1 for incorrect

**Comment by meyerjp3** [comment]
The best thing to do is study the test cases. Also, considering reading more about person scoring in item response theory. Details of the joint maximum likelihood estimation algorithm may be found in Meyer & Hailey (2012) , http://europepmc.org/abstract/MED/23234828  The book Applied Measurement with jMetrik also provide more details about the procedures in the psychometrics library. Finally, read the API, http://www.itemanalysis.com/api/psychometrics/. It is a little out of date, but it contains teh information you need to answer your questions.
