### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dietzc** [meyerjp3/psychometrics#8]
Hi,

is there any license available for this project? It would be great if this projected would be licensed under BSD, Apache Common License, LGPL or MIT.

Thank you for your work :+1: 

Christian

**Comment by wbuchanan** [comment]
@dietzc It seems like this is covered a bit in the project's README:

> A Java library for psychometric analysis. View the psychometrics API to learn more about the library. It includes mathematical and statistical procedures that are not part of the Apache commons math library. It is a key component of jMetrik an open source application for psychometrics. See http://www.ItemAnalysis.com for more information about jMetrik and the psychometrics library.

> Recommended Citation:

> Meyer, J. P. (2015). Psychometrics: An open source JavaTM library for measurement [computer software]. Available from https://github.com/meyerjp3/psychometrics.

I think it would be safe to assume that given the nature of the dependencies, the project would be licensed under at least the same license used by the Apache Commons Math library.  You could also check out the related repository for [jMetrik](https://github.com/meyerjp3/jMetrik), which includes a reference to GPL v.2 (the Psychometrics library is the backend for the jMetrik application.

**Comment by dietzc** [comment]
@wbuchanan I'm not sure if you are right. This very repository is not licensed or is the "part of" statement enough to force it to have the same license as `jMetrik`?

> I think it would be safe to assume that given the nature of the dependencies, the project would be licensed under at least the same license used by the Apache Commons Math library. 

I fully agree.

**Comment by wbuchanan** [comment]
@dietzc My understanding was that this library was developed to create jMetrik.  This library is a major part of the jMetrik license, so my assumption would be that you could treat it similarly.  I'm not trying to speak on behalf of the library creator, but instead suggesting that from my experience the author of the library is fairly accomodating and you could probably start any development without too many worries;  that said, my particular project is focused on building a Stata interface to the library using Stata's Java API and there is no intent to profit from it.  If you were planning on using the library for a product that you would commercially release that may be a bit different of a scenario.

**Comment by dietzc** [comment]
@wbuchanan yes. I know. I'm just not sure, if if you only mention the parent project in the repository,  the license is valid even if you didn't explicitly put the license in the repository itself. If it wouldn't be valid, the repository would be unlicensed and I couldn't use it at all. 

btw. I'm not planning to put it into a product. However, as I'm thinking about using the code in another open-source project, the licensing would be easier to me with Apache license compared to GNU. Pretty annoying :-(

**Comment by meyerjp3** [comment]
Yes, it licensed under the Apache License, Version 2.0. The source code files include the license statement.

**Comment by dietzc** [comment]
great! thanks!
