### ISSUE TITLE
Feature Requests - Many Facet Models

### ISSUE THREAD

**Issue by wbuchanan** [meyerjp3/psychometrics#9]
Hi,

I was wondering if you've considered adding capabilities to fit many Facet Rasch models to the library?  I'm not sure how much effort it would require, but I think it would be a pretty awesome contribution since there doesn't seem to be too many options to fit these types of models without purchasing Facets or rolling your own solution.  It'd also be extraordinarily useful in K-12 education to evaluate rater parameters for observational protocols.

**Comment by meyerjp3** [comment]
I will think about it. It would be nice to add, but my time is limited at the moment.
